services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

    networks:
      - taskflow-network


  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      PORT: "${BACKEND_PORT}"
      JWT_SECRET: "${JWT_SECRET}"
    networks:
      - taskflow-network

  postgres:
    image: postgres:latest

    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pg-db-data:/var/lib/postgresql

    networks:
      - taskflow-network

volumes:
  pg-db-data:

networks:
  taskflow-network:
